### ISSUE TITLE
Failures in ebpf testing on multiple kernels

### ISSUE THREAD

**Issue by lrishi** [elastic/ebpf#125]
Find all failures here: https://github.com/elastic/ebpf/actions/runs/2885114475
Keep the fix within scope.

**Comment by rhysre** [comment]
All failures have been fixed. The problems were as follows:

### Ubuntu cloud kernels
Several 5.11-based Ubuntu cloud kernels (e.g. 5.11.0-1006-aws) did not enable BTF and thus we have no way of supporting them. These had to be weeded out kernel by kernel. There were offending kernels of the `azure`, `aws`, `oracle` and `oem` flavors. They were removed.

### Kali3 kernels

Some 5.10.0 kali3 kernels were included by accident. We only support 5.10.10+. They were removed

### All `PREEMPT_RT` kernels

Fixed by https://github.com/elastic/ebpf/pull/129
